AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  Exclude:
    - ".builders/**/*"
    - "spec/samples/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
